### ISSUE TITLE
Type Error

### ISSUE THREAD

**Issue by Praveen1803** [aimagelab/TransformerBasedGestureRecognition#1]
Hello! I was hoping to implement your cool work by following the steps when I run into multiple errors. I wanted to train the model rather than use the pretrained ones and hence downloaded the Briareo rgb dataset, edited the train.json file in hyperparameters folder and then executed the main.py as suggested and I run into errors as follows:

Traceback (most recent call last):
  File "main.py", line 46, in <module>
    model.init_model()
  File "/home/pm/TransformerBasedGestureRecognition/src/train.py", line 117, in init_model
    self.net = GestureTransoformer(self.backbone, self.in_planes, self.n_classes,
  File "/home/pm/TransformerBasedGestureRecognition/src/models/temporal.py", line 46, in GestureTransoformer
    model = _GestureTransformer(backbone_dict[backbone], in_planes, n_classes, **kwargs)
  File "/home/pm/TransformerBasedGestureRecognition/src/models/temporal.py", line 23, in __init__
    self.self_attention = EncoderSelfAttention(512, 64, 64, **kwargs)
  File "/home/pm/TransformerBasedGestureRecognition/src/models/attention.py", line 106, in __init__
    for _ in range(n_module)])
TypeError: 'NoneType' object cannot be interpreted as an integer

Can you please help with the same as I am having a hard time in interpreting this error in itself. Any guidance would be invaluable. Thanks in advance!

**Comment by Deusy94** [comment]
Hi @Praveen1803, thank you for reaching out!
It seems like the hyperparameters file for the Briareo dataset was not correct.
For instance, the problem is caused by the missing parameters n_module, which if is not present in the json file is loaded as None.

I've now added the missing line now. 634aa453786f9b8595414eda93077b4f6de658b2

**Comment by Praveen1803** [comment]
Hi again @Deusy94  . Apologies for my late reply and thanks for the above commit. The n_module error has been fixed but I seem to be landing on a more primitive error in which the hypes file can't seem to find the data path for training 'rgb' Briareo dataset. I tried all sets of permutations for paths but I still seem to get the file not found error as below:

File "/home/pm/TransformerBasedGestureRecognition/src/train.py", line 172, in init_model
    Dataset(self.configer, self.data_path, split="train", data_type=self.data_type,
  File "/home/pm/TransformerBasedGestureRecognition/src/datasets/Briareo.py", line 47, in __init__
    data = np.load(self.dataset_path / "splits" / (self.split if self.split != "val" else "train") /
  File "/home/pm/.local/lib/python3.8/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/home/pm/GUEST_SHARE/rgb/train/splits/train/rgb_train.npz'


where the path to my Briareo unzipped dataset is : /home/pm/GUEST_SHARE/rgb/train/

Could you please help with the same? Thanks in advance :)

**Comment by Deusy94** [comment]
Thanks for pointing it out @Praveen1803 !! 
It seems like the splits folder wasn't loaded inside the dataset folder, you can download it now from the drive link for the dataset. You then just need to unzip the file in the same folder as the rgb folder. After that all should run smooth, please reach out if something is not working again!

NB! Pull the new version of Birareo source, since I've corrected a small issue with rgb image reading c1b2ecddd7bf00f68c3e1f1e851c26262cc22161

**Comment by Praveen1803** [comment]
Hey @Deusy94 , I have added the splits folder and the execution reaches til Briareo.py before it breaks out into following error:

Loading Briareo TRAIN dataset... done.
Loading Briareo VAL dataset... done.
Loading Briareo TEST dataset... done.
Starting epoch 1
Train:   0%|                                           | 0/936 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 47, in <module>
    model.train()
  File "/home/pm/TransformerBasedGestureRecognition/src/train.py", line 283, in train
    self.__train()
  File "/home/pm/TransformerBasedGestureRecognition/src/train.py", line 194, in __train
    for data_tuple in tqdm(self.train_loader, desc="Train"):
  File "/home/pm/.local/lib/python3.8/site-packages/tqdm/std.py", line 1130, in __iter__
    for obj in iterable:
  File "/home/pm/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/pm/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "/home/pm/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/home/pm/.local/lib/python3.8/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
cv2.error: Caught error in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/pm/.local/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/pm/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/pm/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/pm/TransformerBasedGestureRecognition/src/datasets/Briareo.py", line 91, in __getitem__
    img = cv2.resize(img,(224, 224))
cv2.error: OpenCV(3.4.11) /tmp/pip-req-build-tl4p9sid/opencv/modules/imgproc/src/resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'resize'

There seems to be a problem in finding path or some other issue with image reading as the cv2.resize is getting empty values. I checked by printing image size and it is indeed Nonetype. I tried 'io.imread()' as well with the same kind of problem. The issue seems to be with datapath.
Also, in the _init_ for Briareo.py I changed the datatype= 'rgb' too!
Please let me know how can this be fixed.

Best.

**Comment by Deusy94** [comment]
Hello again, 
there is no reason to change datatype to 'rgb' inside the Dataset script, this should be changed in the config file for the Briareo dataset: `hyperparameters/Briareo/train.json`. There you can swap data type and other hyperparameters for the training.

You should also set up the right location inside that file, for instance, you need to write the correct path for your system, where you downloaded the Briareo dataset: `"data_path": "path/to/Briareo"`.

In the Briareo Dataset class, the rgb images are loaded at the line 99, with `img = cv2.imread(str(self.dataset_path / p))`. You can check that the correct path is being used with a debugger or with a print.
If you need more help on this issue, please add the line `print(str(self.dataset_path / p))` before the line 99, and post here the result so I can further help you!

**Comment by Praveen1803** [comment]
Hey again! Thanks for your quick reply. Like you pointed out, the change in the Dataset class file was an unnecessary change and I got the part about changing the the parameters in the hyperparameter config file. Anyway, your debugging suggestion helped and the path could not be read because of the folder structure of unzipped dataset because I downloaded the 'rgb/splits' folder separately. So it should be like : rgb/ should contain rgb/ & splits/ folder, as in the provided dataset link. 

Thanks you for all your friendly help @Deusy94. Everything seems to work smoothly now.

**Comment by Deusy94** [comment]
No problem at all @Praveen1803 , thank you for reaching out!

**Comment by Praveen1803** [comment]
Hey again @Deusy94 .
This might not be exactly be the right place to ask this but if you still can help I would be extremely grateful as I have spent quite some time on this problem:
Reading the NVDIA Gesture dataset works fine using your provided code, but I am struggling with reading the original dataset using the 'readdata.py' provided within the NVDIA dataset folder. The code seems to have some old dependencies which I tried fixing but unfortunately still gets stuck at reading the path I guess and I was wondering if you could read the same using the script provided by them, as I would very much like to investigate the raw dataset first. If you have the modified file which you used or can suggest the edits so that I can accomplish the same, it would be awesome.
Best,
Praveen

**Comment by Praveen1803** [comment]
Hey again @Deusy94!
Sorry to bother you again. I wanted to read the 'raw' dataset of NVIDIA and tried modifying their provided 'readdata.py' taking inspiration from your code but seem to have stuck at a dead end. Do you think you have the file you used to read their original dataset or can you suggest the edits in the same? (The script would be helpful in pinpointing the issue from my side). The file seems to have some old python dependencies or maybe my opencv libraries/dependencies are not correctly mapped; the execution just breaks out for me and I have been stuck at this one script for a long time now.

It probably does not make sense to post this issue here, but I still wanted to give it a shot for fast fix :). Let me know if you can help. Thanks again!
Best.

**Comment by Deusy94** [comment]
Hi again,
I have the original code from their repository, but I don't see any
problem.
Can you please post your specific error?

Il giorno sab 29 mag 2021 alle ore 20:30 Praveen1803 <
***@***.***> ha scritto:

**Comment by Praveen1803** [comment]
Hey man, I could fix the problem and hence I deleted the query as well . My opencv package could not access the ffmpeg library for reading. Explicitly calling it in the 'cv2' function worked for me.
Thank you and cheers.
