### ISSUE TITLE
result directory

### ISSUE THREAD

**Issue by netzahdzc** [aimagelab/TransformerBasedGestureRecognition#5]
Hi, thank you for sharing your code of such nice work. 

I have successfully run the training/testing scripts shown in the instructions. However, I'm a bit confused as in the train.json file, there is a parameter "result_dir". I manually create the directory however, it remains empty after running `python main.py --hypes hyperparameters/Briareo/train.json --gpu 0 1`. Would you happen to know if this is a bug?

**Comment by stefanopini** [comment]
Hi, thanks for the interest in our work!

I checked and that parameter is indeed unused, it's probably a remnant of a previous project.

Results of the training are saved according to the parameters defined in `"checkpoints"`:
https://github.com/aimagelab/TransformerBasedGestureRecognition/blob/1ea62945666b68f52a1064e2baaaeffd29997e70/src/hyperparameters/Briareo/train.json#L15-L21
- checkpoints are saved in the `save_dir` (see [here](https://github.com/aimagelab/TransformerBasedGestureRecognition/blob/1ea62945666b68f52a1064e2baaaeffd29997e70/src/models/model_utilizer.py#L144))
- tensorboard logs are saved in the `tb_path` (see [here](https://github.com/aimagelab/TransformerBasedGestureRecognition/blob/1ea62945666b68f52a1064e2baaaeffd29997e70/src/train.py#L86))

Please let me know if you find the results of your training in those folders.

**Comment by netzahdzc** [comment]
Hi, thank you for your prompt response!! Yes, checkpoints and tensorboard are saved as expected. Thank you.
