### ISSUE TITLE
Custom dataset

### ISSUE THREAD

**Issue by netzahdzc** [aimagelab/TransformerBasedGestureRecognition#6]
Hi, thank you for the well-organised code; also, congratulation on the interesting paper. At the moment, I am trying to test your code on a customised RGB dataset; I am planning on the scripts available at `/src/dataset/ [Braireo.py and NVGesture.py]`; however, I got confused about the purpose of the `npz` files such as `data/Briareo/splits/test/rgb_test.npz`. Could you briefly elaborate on their purpose, pls? also  **Would I need to create npz file for my customised dataset?**

**Comment by stefanopini** [comment]
Hi again! No, no requirements to create your own npz files.
As you can see here
https://github.com/aimagelab/TransformerBasedGestureRecognition/blob/1ea62945666b68f52a1064e2baaaeffd29997e70/src/datasets/Briareo.py#L47-L62
we use those npz files to store the paths of the files that belong to a specific source (rgb, ir, etc.) and split (train, val, test), and to mark which records are valid. You can modify the code to load your files in any way it is convenient for you.

Please feel free to reopen this issue if this doesn't answer to your question or if you have any other related questions.
