### ISSUE TITLE
Could you elaborate on how to perform late fusion approach for the NvGesture dataset!

### ISSUE THREAD

**Issue by adithya2424** [aimagelab/TransformerBasedGestureRecognition#7]

**Comment by adithya2424** [comment]
The accuracy seems to be too low, unable to figure out what could be the reason
Accuracy: 0.03319502074688797

**Comment by stefanopini** [comment]
Hi @adithya2424 ,

To help figure out the issue, could you please provide more details regarding your setting?
In particular, did you load the pre-trained models or trained from scratch? 
Also, have you tried the single models without late fusion? What is the accuracy in that case?

**Comment by stefanopini** [comment]
Closing, feel free to reopen tagging me if still facing this issue.
